### ISSUE TITLE
Demo launch file debug

### ISSUE THREAD

**Issue by kamiradi** [moveit/moveit_drake#17]
@sea-bass @sjahr I am trying to run the demo with the current state of the build (as of the latest commit in #8 ). I have removed all the default planning pipelines https://github.com/moveit/moveit_drake/pull/8/commits/4a31afe54127577419ba4c04fa970d5cc3ab622a#r1665337870. When running the demo script, I see that the pipeline bench node still loads ompl and stomp. Also, clearly the drake `ktopt_planning` plugin is not being loaded. I have been trying to follow the messages on the ros console but didnt know where to start with this. I may be missing something very silly. Feel free to build and run the demo at the linked commit. Any tips on debugging this?

**Comment by sjahr** [comment]
Can you share the log?

**Comment by kamiradi** [comment]
Ok I think I know what maybe happening, it has something to do with the planning_pipeline options set in the moveit_config builder in the launch file. I see that over there the config options still point to `stomp`, `ompl`, `stomp_ompl`. This needs to be changed to drake.

**Comment by kamiradi** [comment]
I get the following after readding the `ktopt_interface/KTOptPlanner` to the ompl_stomp pipeline. The rest of them load, however the plugin is not being found. Where else am I supposed to expose the ktopt_plugin, any clues?
```
[pipeline_testbench_example-4]   what():  According to the loaded plugin descriptions the class ktopt_interface/KTOptPlanner with base class type planning_interface::PlannerManager does not exist. Declared types are  chomp_interface/CHOMPPlanner ompl_interface/OMPLPlanner pilz_industrial_motion_planner/CommandPlanner planning_pipeline_test/DummyPlannerManager stomp_moveit/StompPlanner
```

**Comment by sea-bass** [comment]
Yep, seems like the Drake plugin is not visible.

Usually, this means there is an inconsistency in either the plugin definition in the .cpp file or in the YAML file.
Or, something missing in the CMakeLists.txt.

**Comment by kamiradi** [comment]
Which YAML file would this be?

**Comment by sea-bass** [comment]
> Thanks @sea-bass, which YAML file would this be?

Sorry, the plugin description XML* file

**Comment by sjahr** [comment]
As Sebastian said, you'll need to verify that all namespace and the plugin definition in general is consistent. I'd reiterate with instructions again: https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Pluginlib.html
Unfortunately this is very error prone without good error messaging :disappointed:

**Comment by sea-bass** [comment]
@kamiradi I made a small typo fix in your PR. Now when I run the demo the KTOpt plugin does show!

```
[pipeline_testbench_example-4]   what():  Planning plugin name is empty or not defined in namespace 'ompl_stomp'. Please choose one of the available plugins: chomp_interface/CHOMPPlanner, ktopt_interface/KTOptPlanner, ompl_interface/OMPLPlanner, pilz_industrial_motion_planner/CommandPlanner, planning_pipeline_test/DummyPlannerManager, stomp_moveit/StompPlanner
```

**Comment by sjahr** [comment]
@kamiradi You'll need to update the plugin name here too: https://github.com/moveit/moveit_drake/blob/d80644c55e6afaabaf4a3eb81af0b1b568b52641/demo/config/testbench_moveit_cpp.yaml#L13
