### ISSUE TITLE
Demo cmake configure errors

### ISSUE THREAD

**Issue by kamiradi** [moveit/moveit_drake#19]
@sjahr @sea-bass For some reason, the demo/CMakeLists.txt is throwing the following error. This is a first and as of commit https://github.com/moveit/moveit_drake/pull/18/commits/ffa7384a690cdbad96a1f087af11d3d6a0cc8ad9, and I can't think of anything that I have changed for this to come about. Any clues?

```
Starting >>> moveit_drake
--- stderr: moveit_drake                          
moveit_drake: You did not request a specific build type: Choosing 'Release' for maximum performance
CMake Error at demo/CMakeLists.txt:1 (add_executable):
  Target "pipeline_testbench_example" links to target
  "moveit_core::moveit_butterworth_parameters" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at demo/CMakeLists.txt:1 (add_executable):
  Target "pipeline_testbench_example" links to target
  "moveit_core::moveit_planning_request_adapter" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Generate step failed.  Build files cannot be regenerated correctly.
---
Failed   <<< moveit_drake [9.96s, exited with code 1]

Summary: 0 packages finished [10.6s]
  1 package failed: moveit_drake
  1 package had stderr output: moveit_drake

```

Thought I'd ask before going down CMake rabbit hole. Might have something to do with the fact that I added drake as an option into the demo in this commit https://github.com/moveit/moveit_drake/pull/18/commits/071032eead4da637057d1217be1cab598037fc5c, can you confirm?

**Comment by sea-bass** [comment]
That looks to me like moveit is available from binaries on your system and should be removed.

**Comment by kamiradi** [comment]
Ah, I was hoping I didn't have to rebuild the container, but here goes.

**Comment by kamiradi** [comment]
Yup, was working with an older container. This solves the issue.
