### ISSUE TITLE
`robot_description` subscriber callback not being reached.

### ISSUE THREAD

**Issue by kamiradi** [moveit/moveit_drake#20]
Hi @sjahr @sea-bass , as of https://github.com/moveit/moveit_drake/pull/18/commits/4dcb2169669438bf07c5619debb63798643b342f, I have made a few changes to log and report robot_description status. It seems that the callback to the `robot_description` subscription is not being called. I see that the ktopt planner manager is being initialized, however the lambda that implements the callback to the robot_description subcription does not get executed. Do you guys see something that I don't see?

**Comment by sjahr** [comment]
Is the description published? If yes, as a very dirty workaround you could create a string in the ktop cpp file with the copy&pasted config and use that for the multibody plant (intermediately). I can maybe take a look into the publisher issue on the weekend

**Comment by kamiradi** [comment]
Yes it is! I'll do that

**Comment by kamiradi** [comment]
Solved in #18 and https://github.com/moveit/moveit_drake/pull/18/commits/ad817c26f72dcf254d864301eb3c8c0d1bd20e7c
