### ISSUE TITLE
[Cleanup] Add relevant docstrings to plugin

### ISSUE THREAD

**Issue by kamiradi** [moveit/moveit_drake#21]
add docstrings to these

_Originally posted by @sea-bass in https://github.com/moveit/moveit_drake/pull/18#discussion_r1678459172_

**Comment by kamiradi** [comment]
@sea-bass @sjahr Any reference file for docstrings in mind?

**Comment by sea-bass** [comment]
> @sea-bass @sjahr Any reference file for docstrings in mind?

Whatever moveit uses, like this:

https://github.com/moveit/moveit2/blob/main/moveit_planners/stomp/include/stomp_moveit/conversion_functions.hpp#L86
