### ISSUE TITLE
Which branch of `moveit2_tutorials`?

### ISSUE THREAD

**Issue by galou** [moveit/moveit_drake#3]
I'm missing at least `moveit2_tutorials/config/testbench_moveit_cpp.yaml` and the executable `pipeline_testbench_example` from `moveit2_tutorials`. Which branch/repo of `moveit2_tutorials` are you using?

**Comment by sjahr** [comment]
@galou Sorry for the late response. This repository does not require the moveit2_tutorials but there were some errors in the launch files that lead to a misleading error message. This PR fixes it: https://github.com/moveit/moveit_drake/pull/7
