### ISSUE TITLE
Use RobotModel joint limits and support acceleration (and maybe jerk) constraints

### ISSUE THREAD

**Issue by sea-bass** [moveit/moveit_drake#45]
Add joint position, velocity and acceleration limits.

**Comment by kamiradi** [comment]
@sea-bass @sjahr I remember that you had shown way to get these limits from RobotModel. Can you comment with necessary links for the sake of documentation and implementation.

Current options include
- Reading it from the URDF/SRDF directly
- VariableBounds within `robot_model::JointModel` class

Any other option I may be missing, or correction in the existing?

**Comment by sea-bass** [comment]
You can extract them from the robot model as in here: https://github.com/moveit/moveit2/blob/489d99617932a453057c03134e04e68092b8a189/moveit_ros/moveit_servo/src/utils/common.cpp#L390
